spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nprox?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.nixer.nprox: debug  # 打印sql语句
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.npro.clientserver.entity
#jwt
jwt:
  header: Authorization
  expiration: 86400
  # 令牌前缀
  token-start-with: Bearer
  secret: Zmpqc2Q9ODcyZHNkZjIzM2OkNFJFUkZhMzIzMjQzMlJkaWHzMnIyMzk4dTMyamZra3NXMjMxM1QyMzMmKiZqZUxKRiZeKjFHTExQO0RKODk4NDNqcmUoKGlvZXdqZktKRE8zMnhjY08yS0ZLTlNmZ2hqb3AtPTFSV0VIUkVXRVc=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时
  token-validity-in-seconds: 14400000
  tokenHead: "Bearer "
